name: esc_pos_bluetooth
description: The library allows to print receipts using an ESC/POS thermal Bluetooth printer.
version: 0.4.3
homepage: https://github.com/andrey-ushakov/esc_pos_bluetooth

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_basic:
    git:
      url: https://github.com/CharindiDulmini/flutter_bluetooth_basic.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
